"""add Healer model

Revision ID: 1ca0d3d0b30e
Revises: 7c2c9bedd1a3
Create Date: 2023-05-09 09:59:56.866246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca0d3d0b30e'
down_revision = '7c2c9bedd1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healer')
    # ### end Alembic commands ###
